services:
  # Service AssemblyScript (S1-S2)
  wasm-as:
    # Au lieu d'une image, on indique comment construire
    build:
      context: .
      dockerfile: Dockerfile.as
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    # Plus besoin de 'command' ici, le Dockerfile s'en charge !

  # Service C++ (S3-S8) - Inchangé
  wasm-cpp:
    image: emscripten/emsdk:3.1.51
    working_dir: /app
    platform: linux/amd64
    volumes:
      - ./:/app
    command: tail -f /dev/null
